export const data = [    
    {"id": 1,
      "client_name": "John Smith",
              "title": "Build a Website",
              "description": "Create a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small business",
              "budget": 5000.00,
              "deadline": "2023-05-31T23:59:59",    
              "num_bid": 3
          },
          { "id": 2,   
            "client_name": "Jane Doe",
              "title": "Logo Design",
              "description": "Create a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small business",
              "budget": 1000.00,
              "deadline": "2023-06-15T23:59:59",    
              "num_bid": 3
          },
          { "id": 3,      
             "client_name": "Bob Johnson",
              "title": "Marketing Campaign",
              "description": "Create a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small business",
              "budget": 15000.00,
              "deadline": "2023-07-31T23:59:59",    
              "num_bid": 3
          },
          { "id": 4,     
              "client_name": "Alice Brown",
              "title": "Mobile App Development",
              "description": "Create a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small business",
              "budget": 20000.00,
              "deadline": "2023-08-30T23:59:59",    
              "num_bid": 3
          },
          { "id": 5,     
             "client_name": "Charlie Lee",
              "title": "Social Media Management",
              "description": "Create a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small business",
              "budget": 8000.00,
              "deadline": "2023-06-30T23:59:59",    
              "num_bid": 3
          },
          { "id": 6,      
             "client_name": "Emily Jones",
              "title": "E-commerce Website Development",
              "description": "Create a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small business",
              "budget": 25000.00,
              "deadline": "2023-09-30T23:59:59",    
              "num_bid": 3
          },
          { "id": 7,      
             "client_name": "David Kim",
              "title": "Video Production",
              "description": "Create a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small business",
              "budget": 5000.00,
              "deadline": "2023-07-15T23:59:59",    
              "num_bid": 3
          },
          { "id": 8,      
             "client_name": "Sarah Garcia",
              "title": "Content Writing",
              "description": "Create a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small business",
              "budget": 3000.00,
              "deadline": "2023-05-31T23:59:59",    
              "num_bid": 3
          },
          { "id": 9,      
             "client_name": "Mark Taylor",
              "title": "Graphic Design",
              "description": "Create a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small business",
              "budget": 2000.00,
              "deadline": "2023-06-30T23:59:59",    
              "num_bid": 3
          },
          { "id": 10,     
              "client_name": "Linda Chen",
              "title": "UI/UX Design",
              "description": "Create a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small businessCreate a responsive website for a small business",
              "budget": 12000.00,
              "deadline": "2023-08-31T23:59:59"    
            }]